~VERSION INFORMATION
VERS.                                                 2.0:   CWLS Log ASCII Standard-VERSION 2.0
WRAP.                                                  NO:   One line per depth step
~Well Information Block
STRT.M                                           316.1264:   Top Depth
STOP.M                                          1613.2028:   Bottom Depth
STEP.M                                             .15240:   Depth Increment
NULL.                                            -999.250:   Null Value
FLD .                                               Q7125:   Field Name
WELL.                                            7125/4-1:   NAME
WBN .                                            7125/4-1:   WELLBORE
NATI.                                                 NOR:   COUNTRY
APD .M                                               23.0:   ABOVE PERM DATUM
LOC .                                         BARENTS SEA:   AREA NAME
CTRY.                                                 NOR:   COUNTRY
COMP.                                           HYDRO ASA:   OPERATOR
PDAT.                                                 MSL:   PERM DATUM
COUN.                                       POLAR PIONEER:   RIG NAME
STAT.                                       POLAR PIONEER:   STATE
LATI.                            071 33' 00.800" N    DMS:   SURF. LATITUDE
LONG.                            025 14' 22.320" E    DMS:   SURF. LONGITUDE
PBWE.                                            7125/4-1:   PB WELL ID
APIN.                                            7125/4-1:   PB WELLBORE ID
PBWS.                                                 ALL:   PB WELL NAME SET
~PARAMETER INFORMATION (log)
LNAM.                                       WLC_COMPOSITE:   NAME
LTYP.                                                PAP.:   LOG TYPE
LSRV.                                              WL.LOG:   LOG SERVICE
LSOU.                                               HYDRO:   LOG SOURCE
LVSN.                                                   1:   LOG VERSION
BHIS.                                                  RC:   BRIEF HISTORY
R1  .       COMPOSITE SPLICED DATA CONSISTS OF THE FOLLOW:   COMMENT  1
R2  .                         MWD ARC-ISONIC, RUN 1, 4-5.:   COMMENT  2
R3  .                               MWD ARC-RAB, RUN 6-9.:   COMMENT  3
R4  .                         EWL DSI-TLD-CNL-GR, RUN 1A.:   COMMENT  4
R5  .            EWL CMR-HRLA-TLD-CNL-ECS-HNGS, RUN 2A/B.:   COMMENT  5
R6  .                       EWL TLD-CNL-ECS-HNGS, RUN 3F.:   COMMENT  6
R7  .                    EWL FMI-GR-APS-PPC-MSIP, RUN 2A.:   COMMENT  7
R8  .                         EWL MSIP-PROCESSED, RUN 2A.:   COMMENT  8
R9  .                       EWL MSIP-PROCESSED, RUN 3C/F.:   COMMENT  9
EDF .M                                               23.0:   ELEV DRILL FLOOR
ELZ .M                                               23.0:   ELEVATION LOG ZERO
FHIS.                                        RAW-LIS/COPY:   FULL HISTORY
EKB .M                                               23.0:   KB ELEVATION
LMF .                                                  KB:   LOGS MEAS FROM
EPD .M                                                0.0:   ELEV PERM DATUM
EGL .M                                             -293.0:   GROUND LEVEL
QCRM.                   WAITING FOR OPERATOR CONFIRMATION:   QC COMMENT
QCCO.                                               HYDRO:   QC COMPANY
~Curve Information Block
#MNEM.UNIT                                        API CODE    No Description
#=========                                        ========    == ===========
DEPT.M                                       00 001 00 00:     1  DEPTH
AC.US/F                                                  :     2  Sonic Transit Time (Slowness)
ACS.US/F                                                 :     3  Unrecognised
BS.IN                                                    :     4  Nominal Bit Size
CALI.IN                                                  :     5  Caliper
DEN.G/CC                                                 :     6  Bulk Density
DENC.G/CC                                                :     7  Density Correction
GR.GAPI                                                  :     8  Gamma Ray
K.V/V                                                    :     9  Potassium
NEU.V/V                                                  :    10  Unrecognised
PEF.B/E                                                  :    11  Photo-Electric Factor
RDEP.OHMM                                                :    12  Unrecognised
RMED.OHMM                                                :    13  Unrecognised
RMIC.OHMM                                                :    14  Unrecognised
ROP.M/H                                                  :    15  ROP
TH.PPM                                                   :    16  Spectral Gamma Ray Curve
U.PPM                                                    :    17  Spectral Gamma Ray Curve
~ASCII
  316.1264   207.4673  -999.2500     9.8750  -999.2500  -999.2500  -999.2500     3.9980  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     4.8645  -999.2500  -999.2500
  316.2788   207.4418  -999.2500     9.8750  -999.2500  -999.2500  -999.2500     5.1227  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     5.1242  -999.2500  -999.2500
  316.4312   208.8660  -999.2500     9.8750  -999.2500  -999.2500  -999.2500     6.2474  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     5.3838  -999.2500  -999.2500
  316.5836   209.3216  -999.2500     9.8750  -999.2500  -999.2500  -999.2500     8.1828  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     5.6435  -999.2500  -999.2500
  316.7360   207.4403  -999.2500     9.8750  -999.2500  -999.2500  -999.2500    12.6901  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     5.9031  -999.2500  -999.2500
  316.8884   205.8846  -999.2500     9.8750  -999.2500  -999.2500  -999.2500    21.5817  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     6.1628  -999.2500  -999.2500
  317.0408   204.9793  -999.2500     9.8750  -999.2500  -999.2500  -999.2500    32.7354  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     6.4224  -999.2500  -999.2500
