~VERSION INFORMATION
VERS.                                                 2.0:   CWLS Log ASCII Standard-VERSION 2.0
WRAP.                                                  NO:   One line per depth step
~Well Information Block
STRT.M                                              .0488:   Top Depth
STOP.M                                          1561.8440:   Bottom Depth
STEP.M                                             .15240:   Depth Increment
NULL.                                            -999.250:   Null Value
FLD .                                               Q7125:   Field Name
WELL.                                            7125/4-1:   NAME
WBN .                                            7125/4-1:   WELLBORE
NATI.                                                 NOR:   COUNTRY
APD .M                                                 23:   ABOVE PERM DATUM
CTRY.                                                 NOR:   COUNTRY
COMP.                                           HYDRO ASA:   OPERATOR
PDAT.                                      Mean Sea Level:   PERM DATUM
UWI .                                            7125/4-1:   WELL NUMBER
PBWE.                                            7125/4-1:   PB WELL ID
APIN.                                            7125/4-1:   PB WELLBORE ID
PBWS.                                                 ALL:   PB WELL NAME SET
~PARAMETER INFORMATION (log)
LNAM.                             VELOCITY_TZV_DEPTH_COMP:   NAME
LTYP.                                                PAP.:   LOG TYPE
LSRV.                                       WL.WS.VEL.LOG:   LOG SERVICE
LVSN.                                                   1:   LOG VERSION
BHIS.                                                   R:   BRIEF HISTORY
EDF .M                                                 23:   ELEV DRILL FLOOR
FHIS.                                            RAW-DLIS:   FULL HISTORY
EKB .M                                                 23:   KB ELEVATION
LMF .                                                  KB:   LOGS MEAS FROM
EPD .M                                                  0:   ELEV PERM DATUM
EGL .M                                            -999.25:   GROUND LEVEL
~Curve Information Block
#MNEM.UNIT                                        API CODE    No Description
#=========                                        ========    == ===========
DEPT.M                                       00 001 00 00:     1  DEPTH
ADJS.S                                                   :     2  Adjusted Sonic Travel Time
AIMP.KPSM                                                :     3  Acoustic Impedance
ATTE.                                                    :     4  Attenuation Coefficient
BS.IN                                                    :     5  Bit Size
CALI.IN                                                  :     6  Caliper
DT.US/F                                                  :     7  Delta-T (also called Slowness or Interva
DTCO.US/F                                                :     8  Delta-T Compressional
DTSM.US/F                                                :     9  Delta-T Shear
MSFL.OHMM                                                :    10  Micro-spherically-focused Resistivity
NPHI.FRAC                                                :    11  Thermal Neutron Porosity (original Ratio
REFL.                                                    :    12  Reflection Coefficient
RT.OHMM                                                  :    13  True Resistivity
RXO.OHMM                                                 :    14  Flushed Zone Resistivity
~ASCII
     .0488  -999.2500  1630.7023     1.0000  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500    -1.0000  -999.2500  -999.2500
     .2012  -999.2500  1630.7021     1.0000  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     -.8000  -999.2500  -999.2500
     .3536  -999.2500  1630.7021     1.0000  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     -.6000  -999.2500  -999.2500
     .5060  -999.2500  1630.7020     1.0000  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     -.4000  -999.2500  -999.2500
     .6584  -999.2500  1630.7020     1.0000  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500     -.2000  -999.2500  -999.2500
     .8108  -999.2500  1630.7019     1.0000  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500      .0000  -999.2500  -999.2500
     .9632  -999.2500  1630.7019     1.0000  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500  -999.2500      .0000  -999.2500  -999.2500
